# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U8MdINItN95uD3r_yElIjUiOhaJ38TGq
"""

import pickle
import numpy as np
import pandas as pd

from flask import Flask,request,jsonify,render_template

model = pickle.load(open('model.pkl','rb'))
app = Flask(__name__)

@app.route('/')
def home():
   return  "Hello World"

# @app.route('/predict',methods=['POST'])

# def predict():
#     features=[x for x in request.form.values()]
#     final_features=[np.array(features)]
#     #prediction=mod.predict(final_features)
#     final_pred = model.predict(pd.DataFrame(columns=['bp','med_bp','urination','hunger','wgt_loss','fatigue','burn','sores','agediv_less_than_30','agediv_less_than_60','agediv_more_than_60'],data=final_features))[0]
#     return jsonify({'Diabetic:':str(final_pred)})



app.run(port=5000)
